# Generated by Django 2.2.2 on 2019-10-17 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20190817_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegedata',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
