# Generated by Django 3.0 on 2019-12-21 19:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0004_relation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='requesting',
            new_name='requestMaker',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='requested',
            new_name='requestReciever',
        ),
        migrations.AlterUniqueTogether(
            name='requests',
            unique_together={('requestMaker', 'requestReciever')},
        ),
    ]
