# Generated by Django 3.0 on 2019-12-23 19:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0006_auto_20191222_0055'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requests',
            unique_together={('requestMaker', 'requestReceiver', 'statusid')},
        ),
    ]
