# Generated by Django 3.0 on 2019-12-23 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_auto_20191224_0100'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requests',
            unique_together=set(),
        ),
    ]
