# Generated by Django 2.2.2 on 2019-08-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='requested',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='requests',
            name='requesting',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='requests',
            unique_together={('requesting', 'requested')},
        ),
    ]
