# Generated by Django 2.2.2 on 2019-08-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('postid', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True)),
                ('createdon', models.DateTimeField()),
            ],
        ),
    ]
