# Generated by Django 3.0 on 2019-12-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_collegedata_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegedata',
            name='mobile',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collegedata',
            name='clgid',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, unique=True),
        ),
    ]
