# Generated by Django 3.0 on 2020-01-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_auto_20191226_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='uniId',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
