# Generated by Django 3.0 on 2020-01-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_userdata_uniid'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegedata',
            name='uniId',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
