# Generated by Django 3.0 on 2020-04-04 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_collegedata_uniid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeDepartmet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clgid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.CollegeData')),
                ('deptid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.DepartmentData')),
            ],
        ),
    ]
