# Generated by Django 3.0 on 2020-04-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_collegedepartmet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollegeDepartmet',
            new_name='CollegeDepartment',
        ),
    ]
